export const CONTENT =
  {
    intro: 'Junious “House” Brickhouse is an internationally established educator, choreographer and cultural preservationist with over 30 years of experience in Urban Dance Culture.',
    childhood: 'Born in Virginia Beach, VA, his dance training began at family gatherings dancing the funk styles of the era. Growing up, he sought out all the learning opportunities available to him, from community centers to parking lots, where young people were teaching each other and building communities around urban dance forms. Early on, he established himself as a leader and mentor in those communities, serving to educate and guide others.',
    army: 'At age 18, Junious Brickhouse embarked on an over 20-year career as a logistics professional in the U.S. Army and later as a Department of Defense contractor. Throughout this time in various international assignments, Junious developed both a military and dance career, eventually rising to positions of leadership and responsibility in both areas. The logistics skills and leadership acumen Junious honed in his military work provide a solid and unique foundation as a leader and facilitator in the dance world.',
    urbanArtistry: 'As Founder and Executive Director of Urban Artistry Inc. (www.urbanartistry.org). Junious has inspired and created a movement of artists dedicated to the authentic preservation of urban dance culture, specifically within communities of practice. While constantly engaged in research about urban dance culture and the communities from which it evolved, Junious created projects such as The Preservatory and the UA Digital Archives to encourage other artists to research and document these tradition bearers and their stories.',
    nextLevel: 'Brickhouse brought his expertise to Next Level in 2014, its inaugural season, as an Artist Educator for the Senegal program. The potential to serve global communities and shape the global future of Hip Hop inspired Brickhouse to continue to work with Next Level. Since then, Brickhouse has contributed his knowledge and skill to building the program as a Consultant, Site Manager, Associate Director, Co-Director, and now Director.',
    accomplishments: 'Brickhouse continues to serve as Executive Director of Urban Artistry, which was recently featured at the Library of Congress and the National Museum of African American History. He also sits on advisory panels for the National Endowment for the Arts and The American Folklore Society. As a member of Phil Wiggins Blues House Party, Brickhouse takes part in performances and educational programs, sharing the connection between blues music and dance.'
  }
