export const CONTENT =
  {
    intro: 'Junious “House” Brickhouse is an internationally established educator, choreographer and cultural preservationist with over 30 years of experience in Urban Dance Culture.',
    childhood: 'I am a tradition-bearer, and as a tradition-bearer I have a charge to sustainability. That requires connecting with people and creating the infrastructure in which our minds and our diversity can thrive. Having started dancing in the 70’s, I’m from a time where we were motivated differently. Our motivation was not stardom, but rather to be seen and to be respected. I’m from humble beginnings, and I’ve come a long way. Although I’ve enjoyed the journey, the work isn’t done.',
    mother: 'Here is some info about my amazing mom. It is is latin thought. Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, provident iure nemo excepturi magni iusto quos dolores similique, totam explicabo dicta recusandae reprehenderit saepe. Rerum quasi modi nisi facere cum.',
    army: 'At age 18, Junious Brickhouse embarked on an over 20-year career as a logistics professional in the U.S. Army and later as a Department of Defense contractor. Throughout this time in various international assignments, Junious developed both a military and dance career, eventually rising to positions of leadership and responsibility in both areas. The logistics skills and leadership acumen Junious honed in his military work provide a solid and unique foundation as a leader and facilitator in the dance world.',
    assassins: 'Junious joined the Assassins Crew in 2000, while living abroad in Heidelberg, Germany. It was an effort for us to remember the roots of the music and the dance forms we were doing and the people in those communities that were sharing with us. We were a conglomerate of professionals and up-and-coming movers and shakers coming together to represent not just on stages and in the industry but in the underground as well, where these dance forms came from. We were not just trying to be successful as artists, we wanted to be community-driven, so taking care of the underground and the people there was important to us. Those lessons and those people inspired Junious not only to open an Assassins chapter in DC but also to found his own organization, Urban Artistry, dedicated to sharing and preserving these dance cultures.',
    urbanArtistry: 'Upon returning to the US in 2005 following 10 years of working abroad, Junious wanted to continue his community organizing around promoting dance cutlure… here in the US. wanted to build communities in the US to promote dance cultures with origins in African American communities through structured mentorship, professional development, and community-building. He founded the non-profit Urban Artistry, Inc., which has been promoting and preserving dance communities in the DMV area and beyond through classes, mentorship, performances, annual events such as the International Soul Society festival, and partnerships with organizations like the Smithsonian Institution and National Park Service to expand the reach of this programming to new and diverse audiences.',
    nextLevel: 'Brickhouse brought his expertise to Next Level in 2014, its inaugural season, as an Artist Educator for the Senegal program. The potential to serve global communities and shape the global future of Hip Hop inspired Brickhouse to continue to work with Next Level. Since then, Brickhouse has contributed his knowledge and skill to building the program as a Consultant, Site Manager, Associate Director, Co-Director, and now Director.',
    accomplishmentsFull: 'Brickhouse continues to serve as Executive Director of Urban Artistry, which was recently featured at the Library of Congress and the National Museum of African American History. He also sits on advisory panels for the National Endowment for the Arts and The American Folklore Society. As a member of Phil Wiggins Blues House Party, Brickhouse takes part in performances and educational programs, sharing the connection between blues music and dance.',
    accomplishmentsPart1: 'Brickhouse continues to serve as Executive Director of Urban Artistry, which was recently featured at the Library of Congress and the National Museum of African American History. He also sits on advisory panels for the National Endowment for the Arts and The American Folklore Society.',
    accomplishmentsWiggins: 'As a member of Phil Wiggins Blues House Party, Brickhouse takes part in performances and educational programs, sharing the connection between blues music and dance.'
  }
